import Foundation
import os.log

/// Per-bucket phrase cache for instant generation.
///
/// The cache holds **only** phrases generated by Apple Foundation Models (kept
/// warm by `GenerationRefillCoordinator`). `pop()` returns in <1ms; every pop
/// schedules a background refill so the next call is instant too.
///
/// There is no offline seed and no fallback pool. On a cold cache the first
/// generation falls through to a **live** Foundation Models call (~1s); that
/// run also fills the cache, so every subsequent call for that bucket is
/// instant until the user drains it faster than refill keeps up. This is what
/// makes the on-device model actually run — and what makes its ANE/GPU cost
/// real rather than reading a static list.
@MainActor
public final class BucketCache: @unchecked Sendable {
    public static let shared = BucketCache()

    private static let log = Logger(subsystem: "com.signoff", category: "BucketCache")
    private static let maxCacheSize = 5
    private static let refillThreshold = 2

    /// How many new phrases a background refill should produce per bucket.
    public static let fillCount = 3

    private var caches: [String: BucketEntry] = [:]

    public struct BucketEntry: Sendable {
        public var phrases: [String]
        public var source: GenerationProviderKind
        public var lastRefilled: Date

        public var count: Int { phrases.count }

        public init(phrases: [String], source: GenerationProviderKind = .foundationModels) {
            self.phrases = phrases
            self.source = source
            self.lastRefilled = Date()
        }
    }

    /// A cache pop result — phrase plus where it came from. Only one provider
    /// exists now (Foundation Models), but the shape stays so the badge code
    /// never lies about origin.
    public struct CacheHit: Sendable, Equatable {
        public let phrase: String
        public let source: GenerationProviderKind
    }

    public init() {}

    /// Pop a phrase from the cache for the given bucket.
    /// Returns nil if the cache is empty — the caller then runs a live
    /// Foundation Models generation. There is no static fallback.
    public func pop(bucketId: String) -> CacheHit? {
        guard var entry = caches[bucketId], !entry.phrases.isEmpty else {
            Self.log.info("[BucketCache] pop: MISS for bucketId=\(bucketId, privacy: .public)")
            return nil
        }
        let phrase = entry.phrases.removeFirst()
        let source = entry.source
        caches[bucketId] = entry
        Self.log.info("[BucketCache] pop: HIT for bucketId=\(bucketId, privacy: .public), phrase=\(phrase, privacy: .public), remaining=\(entry.phrases.count, privacy: .public), cacheKeys=\(Array(self.caches.keys), privacy: .public)")
        return CacheHit(phrase: phrase, source: source)
    }

    /// Pre-fill the cache for a bucket with phrases, tagging their origin.
    public func fill(bucketId: String, phrases: [String], source: GenerationProviderKind = .foundationModels) {
        var current = caches[bucketId] ?? BucketEntry(phrases: [], source: source)
        var merged = current.phrases
        for phrase in phrases {
            let norm = ProviderResponseGuard.sanitizeSignoff(phrase.trimmingCharacters(in: .whitespacesAndNewlines))
            guard !norm.isEmpty, !merged.contains(norm) else { continue }
            merged.append(norm)
        }
        current.phrases = Array(merged.suffix(Self.maxCacheSize))
        current.source = source
        current.lastRefilled = Date()
        caches[bucketId] = current
        // Log the sanitized phrases
        let sanitized = phrases.map { ProviderResponseGuard.sanitizeSignoff($0) }
        Self.log.info("[BucketCache] fill: bucketId=\(bucketId, privacy: .public), added=\(sanitized, privacy: .public), total=\(current.phrases.count, privacy: .public), cacheKeys=\(Array(self.caches.keys), privacy: .public)")
    }

    /// Warm up all buckets at launch by asking Foundation Models to fill them
    /// in the background. Nothing blocks cold launch, and **nothing is seeded
    /// from a static list** — if a bucket has no cache yet, its first
    /// generation is a real on-device call that also fills the cache.
    public func warmup(buckets: [Bucket], profile: UserProfileSnapshot?, ageGroup: AgeGroup = .genZ) {
        Self.log.info("[BucketCache] warmup: starting for \(buckets.count, privacy: .public) buckets")
        let voiceSnapshot = PromptComposer.VoiceProfileSnapshot(from: VoiceProfile.shared)
        for bucket in buckets {
            Self.log.info("[BucketCache] warmup: requesting refill for bucket=\(bucket.id, privacy: .public)")
            requestFMFRefill(bucket: bucket, profile: profile, ageGroup: ageGroup, voiceSnapshot: voiceSnapshot)
        }
    }

    private func requestFMFRefill(bucket: Bucket, profile: UserProfileSnapshot?, ageGroup: AgeGroup, voiceSnapshot: PromptComposer.VoiceProfileSnapshot) {
        guard let template = PromptTemplate.load(bucket: bucket.id) ?? .fallback as PromptTemplate? else { return }
        let existing = caches[bucket.id]?.phrases ?? []
        Self.log.info("[BucketCache] requestFMFRefill: bucket=\(bucket.id, privacy: .public), template.system=\(template.system.prefix(50), privacy: .public)")
        GenerationRefillCoordinator.shared.refillIfNeeded(
            bucketId: bucket.id,
            template: template,
            profile: profile ?? UserProfileSnapshot(profile: nil),
            recentTexts: existing,
            config: .init(
                unhingedLevel: bucket.unhingedLevel,
                toneValue: bucket.toneValue,
                customInstructions: bucket.customInstructions,
                phraseList: bucket.phraseListJSON,
                postfixMode: bucket.postfixMode
            ),
            ageGroup: ageGroup,
            voiceProfile: voiceSnapshot,
            fillCount: Self.maxCacheSize
        )
    }

    /// Get cache stats for diagnostics.
    public func stats(bucketId: String) -> (count: Int, source: GenerationProviderKind?, lastRefilled: Date?) {
        guard let entry = caches[bucketId] else { return (0, nil, nil) }
        return (entry.count, entry.source, entry.lastRefilled)
    }

    /// Clear all cached phrases — used on launch to flush stale pre-sanitization entries.
    public func clearAll() {
        Self.log.info("[BucketCache] clearAll: clearing all caches")
        caches.removeAll()
    }
}
