import Foundation
#if canImport(FoundationModels)
import FoundationModels
#endif

/// Coordinates background refills of the per-bucket phrase cache with phrases
/// generated by Apple Foundation Models. This is what makes Signoff feel
/// instant: `pop()` returns a cached, *on-device-generated* phrase (<1ms), and
/// this coordinator writes the next one in the background so the cache never
/// runs dry.
///
/// The cache starts empty and is filled *only* by the on-device model. There is
/// no static phrasebook — if the model isn't ready yet, the bucket simply
/// stays cold until it's available, then the first foreground generation fills
/// it and this coordinator keeps it warm.
@MainActor
public final class GenerationRefillCoordinator {
    public static let shared = GenerationRefillCoordinator()

    private var inflight: Set<String> = []

    public init() {}

    /// Snapshot of the per-request inputs a refill needs to produce a phrase
    /// indistinguishable from a foreground generation.
    public struct BucketGenConfig: Sendable {
        public let unhingedLevel: UnhingedLevel?
        public let toneValue: Double?
        public let customInstructions: String?
        public let phraseList: String?
        public let postfixMode: BucketPostfixMode
        public let nsfwEnabled: Bool

        public init(unhingedLevel: UnhingedLevel? = nil,
                    toneValue: Double? = nil,
                    customInstructions: String? = nil,
                    phraseList: String? = nil,
                    postfixMode: BucketPostfixMode = .nothing,
                    nsfwEnabled: Bool = false) {
            self.unhingedLevel = unhingedLevel
            self.toneValue = toneValue
            self.customInstructions = customInstructions
            self.phraseList = phraseList
            self.postfixMode = postfixMode
            self.nsfwEnabled = nsfwEnabled
        }

        public static let basic = BucketGenConfig()
    }

    /// Request a background fill of `bucketId`'s cache with up to `fillCount`
    /// Foundation Models phrases. The model actually runs each time so the
    /// output varies. No-op if a refill is already inflight for this bucket or
    /// if the on-device model isn't ready.
    public func refillIfNeeded(bucketId: String,
                               template: PromptTemplate,
                               profile: UserProfileSnapshot,
                               recentTexts: [String],
                               config: BucketGenConfig,
                               ageGroup: AgeGroup = .genZ,
                               voiceProfile: PromptComposer.VoiceProfileSnapshot,
                               fillCount: Int = 3) {
        let log = SignoffLogLogger(.generation)
        log.info("[RefillCoordinator] refillIfNeeded: bucketId=\(bucketId, privacy: .public), inflight=\(self.inflight.contains(bucketId), privacy: .public), available=\(FoundationModelsAvailability.probe() == .available, privacy: .public)")
        guard !inflight.contains(bucketId) else { return }
        guard #available(macOS 26, *) else { return }
        guard case .available = FoundationModelsAvailability.probe() else { return }

        inflight.insert(bucketId)
        Task.detached(priority: .utility) { [weak self] in
            await self?.performRefill(
                bucketId: bucketId,
                template: template,
                profile: profile,
                recentTexts: recentTexts,
                config: config,
                ageGroup: ageGroup,
                voiceSnapshot: voiceProfile,
                fillCount: fillCount)
        }
    }

    // MARK: - Internals

    @available(macOS 26, *)
    nonisolated private func performRefill(bucketId: String,
                                          template: PromptTemplate,
                                          profile: UserProfileSnapshot,
                                          recentTexts: [String],
                                          config: BucketGenConfig,
                                          ageGroup: AgeGroup,
                                          voiceSnapshot: PromptComposer.VoiceProfileSnapshot,
                                          fillCount: Int) async {
        let log = SignoffLogLogger(.generation)
        log.info("[RefillCoordinator] performRefill: bucketId=\(bucketId, privacy: .public), unhingedLevel=\(config.unhingedLevel?.rawValue ?? "nil", privacy: .public), toneValue=\(config.toneValue?.description ?? "nil", privacy: .public), nsfwEnabled=\(config.nsfwEnabled, privacy: .public)")
        log.info("[RefillCoordinator] template.system: \(template.system.prefix(80), privacy: .public)")
        log.info("[RefillCoordinator] template.userVariants count: \(template.userVariants.count, privacy: .public)")
        var generated: [String] = []
        // Grow the avoid-list as we produce phrases so the model varies them.
        var avoid = recentTexts
        for i in 0..<max(1, fillCount) {
            log.info("[RefillCoordinator] performRefill: bucketId=\(bucketId, privacy: .public), iteration=\(i, privacy: .public)")
            let composed = PromptComposer.compose(
                template: template,
                profile: profile,
                recentTexts: avoid,
                unhingedLevel: config.unhingedLevel,
                toneValue: config.toneValue,
                postfixMode: config.postfixMode,
                customInstructions: config.customInstructions,
                phraseList: config.phraseList,
                ageGroup: ageGroup,
                voiceProfile: voiceSnapshot,
                nsfwEnabled: config.nsfwEnabled)
            log.info("[RefillCoordinator] composed.instructions: \(composed.instructions.prefix(100), privacy: .public)")
            log.info("[RefillCoordinator] composed.prompt: \(composed.prompt.prefix(100), privacy: .public)")
            let context = ProviderGenerateContext(
                bucketId: bucketId,
                template: template,
                composed: composed,
                unhingedLevel: config.unhingedLevel,
                toneValue: config.toneValue,
                guardWords: template.guardWords)
            do {
                let phrase = try await FoundationModelsProvider().generate(context)
                let sanitized = ProviderResponseGuard.sanitizeSignoff(phrase)
                log.info("[RefillCoordinator] performRefill: bucketId=\(bucketId, privacy: .public), generated phrase=\(sanitized, privacy: .public)")
                generated.append(sanitized)
                avoid.append(sanitized)
            } catch {
                log.info("[RefillCoordinator] FMF refill for \(bucketId, privacy: .public) interrupted: \(error.localizedDescription, privacy: .public)")
                break
            }
        }
        await MainActor.run {
            self.inflight.remove(bucketId)
            guard !generated.isEmpty else { return }
            BucketCache.shared.fill(bucketId: bucketId, phrases: generated,
                                    source: .foundationModels)
            log.info("[RefillCoordinator] FMF refill +\(generated.count, privacy: .public) for \(bucketId, privacy: .public)")
        }
    }
}
